### ISSUE TITLE
Optional field in queries

### ISSUE THREAD

**Issue by tagomoris** [norikra/norikra#55]
Norikra query exactly matches events which contains all fields in that query.
This restriction works well for almost all cases, but does not work for cases like below:

```
# events
event1: {"type": "user", "data": {"username": "tagomoris"} }
event2: {"type": "bot", "data": {"bottype": "google"} }
```

```sql
--- query
SELECT type, COUNT(DISTINCT data.username), COUNT(DISTINCT data.bottype)
FROM target
WHERE type IN ("user", "bot")
```

To solve this case, I have some options to express that specified field may be missing (null if missing):
1. Special function: `NULLABLE(field)`, `MAYBE_MISSING(field)`, `OPTIONAL(field)`, ...
2. Chained name: `field.NULLABE`, `field.MAYBE_MISSING`, `field.OPTIONAL`, ...

Are there any opinions or ideas? Which one you want? Are there any other naming idea?
Please note your idea.

I'll implement this feature in several weeks, in the way which collect many +1s.

**Comment by tagomoris** [comment]
Now I'm working... https://github.com/norikra/norikra/tree/support-nullable

**Comment by jackxue1** [comment]
very cool. thx.

**Comment by tagomoris** [comment]
This feature `NULLABLE(...)` will be included in next release.

**Comment by jackxue1** [comment]
Nice! Thank you.

**Comment by tagomoris** [comment]
v1.2.0 released!

**Comment by jackxue1** [comment]
If we register queries that use the new NULLABLE(...) function inside CASE...WHEN statements, Norikra engine gives the following error: Unknown single-row function, aggregation function or mapped or indexed property named 'nullable' could not be resolved

**Comment by tagomoris** [comment]
@jackxue1 Could you open a new issue about that problem?
I'll fix it ASAP.

**Comment by tagomoris** [comment]
Fixed. See #63
