### ISSUE TITLE
Need to update performance predefined configuration sets of cli.rb to latest one

### ISSUE THREAD

**Issue by yoheimuta** [norikra/norikra#67]
I think that [output of cli](https://github.com/norikra/norikra/blob/16a968f0d7ebbf34f4f267d33a5377fa291758cb/lib/norikra/cli.rb#L43-L48) is outdated, since [v1.2.2](https://github.com/norikra/norikra/commit/1e34f4004bd69291386adce51c671455e36020e5) was released.

Also, the description of [cli-norikra.html](http://norikra.github.io/cli-norikra.html) is confused that above shows old sets and below shows latest sets.

Thank you for reading.

**Comment by tagomoris** [comment]
Thank you for report!
