### ISSUE TITLE
Ability for cumulative sum aggregation (Table / Named Window support)

### ISSUE THREAD

**Issue by ogibayashi** [norikra/norikra#79]
I have a use case which I want to implement on Norikra, but it seems that current Norikra lacks some functionalities to do it.

The use case is cumulative sum aggregation. For example:
- We have web accesslog which is generated for each access of URLs. like {"path": "/some/path1", "status": 200, ...}
- We want to report cumulative access counts for each URLs today and they want to be updated every minute. (or every time the event happens.)

If I simply want access count every minute, I just create EPL like "SELECT path, count(*) as cnt FROM accesslog GROUP BY path", but what I want is cumulative total of the "cnt". 

I think this can be done using Esper's Table or Named Window functionality like below: (I'm not sure this is the best way using Esper though..)

```
create table access_count_aggregation (path string primary key, total_count count(*) );
into table access_count_aggregation select path, count(*) as total_count from accesslog group by path;

on pattern [every timer:at(*,*,*,*,*)]
select path, total_count from  access_count_aggregation;

# Delete records once a day to keep daily total.
on pattern [ every timer:at(0,0,*,*,*)] 
delete from access_count_aggregation
```

But current Norikra does not support Table or Named Window. 

Actually, I have once fulfilled this requirement by creating custom UDF backed by Redis ([norikra-udf-redis](https://github.com/ogibayashi/norikra-udf-redis)) and store values into Redis, but if Norikra itself supports such calculation, that would be better and might be useful for other Norikra users.

**Comment by tagomoris** [comment]
It seems to be done by 2 queries and loopback target, like this:
```sql
-- LOOPBACK(min_count)
SELECT path, COUNT(*) AS cnt
FROM web_access.win:time_batch(1 min)
GROUP BY path
;
SELECT path, LAST(cnt) cnt, SUM(cnt) AS daily_cnt
FROM min_count.win:time(1 day)
GROUP BY path
```

But I didn't try by myself :P

**Comment by ogibayashi** [comment]
Thank you for your response! I didn't come up with using loopback target. I am now trying this approach. (Not yet got exactly the expected result, but trying)

**Comment by ogibayashi** [comment]
I could do what I want by these queries. I slightly modified your queries because I wanted the daily_cnt to be reset at the beginning of each day.

```
-- LOOPBACK(min_count)
SELECT current_timestamp.roundFloor('day') as timebucket, path, COUNT(*) AS cnt
FROM web_access.win:time_batch(1 min)
GROUP BY path
;
SELECT timebucket, path, LAST(cnt) cnt, SUM(cnt) AS daily_cnt
FROM min_count.win:time(1 day)
WHERE current_timestamp.minus(1 day) <= timebucket
GROUP BY path, timebucket
```

Again, thank you for your advise.

**Comment by tagomoris** [comment]
Great to hear that.
